export const BUILDING_DEFS = [
    {
        type: 'command',
        x: 18,
        y: 18,
        width: 5,
        height: 4,
        label: 'COMMAND CENTER',
        shortLabel: 'COMMAND',
        icon: 'C',
        description: 'Team status',
        district: 'civic',
        visualTier: 'hero',
        labelPriority: 'landmark',
        entrance: { tileX: 20, tileY: 22 },
        visitTiles: [{ tileX: 20, tileY: 22 }, { tileX: 17, tileY: 22 }, { tileX: 23, tileY: 22 }],
    },
    {
        type: 'taskboard',
        x: 23,
        y: 24,
        width: 4,
        height: 3,
        label: 'TASK BOARD',
        shortLabel: 'TASKS',
        icon: 'B',
        description: 'Task status',
        district: 'civic',
        visualTier: 'major',
        labelPriority: 'landmark',
        entrance: { tileX: 25, tileY: 27 },
        visitTiles: [{ tileX: 25, tileY: 27 }, { tileX: 22, tileY: 26 }, { tileX: 27, tileY: 26 }],
    },
    {
        type: 'forge',
        x: 28,
        y: 27,
        width: 4,
        height: 3,
        label: 'CODE FORGE',
        shortLabel: 'FORGE',
        icon: 'F',
        description: 'Code work',
        district: 'workshop',
        visualTier: 'major',
        labelPriority: 'landmark',
        entrance: { tileX: 27, tileY: 27 },
        visitTiles: [{ tileX: 27, tileY: 27 }, { tileX: 28, tileY: 30 }, { tileX: 27, tileY: 30 }],
    },
    {
        type: 'mine',
        x: 18,
        y: 27,
        width: 4,
        height: 3,
        label: 'TOKEN MINE',
        shortLabel: 'MINE',
        icon: 'T',
        description: 'Token usage',
        district: 'resource',
        visualTier: 'major',
        labelPriority: 'landmark',
        entrance: { tileX: 20, tileY: 26 },
        visitTiles: [{ tileX: 20, tileY: 26 }, { tileX: 18, tileY: 30 }, { tileX: 22, tileY: 29 }],
    },
    {
        type: 'archive',
        x: 21,
        y: 14,
        width: 5,
        height: 3,
        label: 'GRAND LORE ARCHIVE',
        shortLabel: 'ARCHIVE',
        icon: 'A',
        description: 'Reading and search',
        district: 'knowledge',
        visualTier: 'hero',
        labelPriority: 'landmark',
        entrance: { tileX: 23, tileY: 17 },
        visitTiles: [{ tileX: 23, tileY: 17 }, { tileX: 20, tileY: 16 }, { tileX: 23, tileY: 18 }],
    },
    {
        type: 'observatory',
        x: 15,
        y: 14,
        width: 4,
        height: 4,
        label: 'RESEARCH OBSERVATORY',
        shortLabel: 'OBSERVATORY',
        icon: '*',
        description: 'External research',
        district: 'knowledge',
        visualTier: 'hero',
        labelPriority: 'landmark',
        entrance: { tileX: 17, tileY: 18 },
        visitTiles: [{ tileX: 17, tileY: 18 }, { tileX: 14, tileY: 17 }, { tileX: 19, tileY: 17 }],
    },
    {
        type: 'portal',
        x: 14,
        y: 25,
        width: 4,
        height: 4,
        label: 'PORTAL GATE',
        shortLabel: 'PORTAL',
        icon: 'O',
        description: 'Browser and remote tools',
        district: 'arcane',
        visualTier: 'hero',
        labelPriority: 'landmark',
        entrance: { tileX: 18, tileY: 26 },
        visitTiles: [{ tileX: 18, tileY: 26 }, { tileX: 13, tileY: 27 }, { tileX: 16, tileY: 29 }],
    },
    {
        type: 'watchtower',
        x: 34,
        y: 14,
        width: 3,
        height: 5,
        label: 'PHAROS COMMIT HARBOR',
        shortLabel: 'COMMIT HARBOR',
        icon: 'L',
        description: 'Commit harbor and sea watch',
        district: 'harbor',
        visualTier: 'hero',
        labelPriority: 'landmark',
        entrance: { tileX: 35, tileY: 19 },
        visitTiles: [{ tileX: 35, tileY: 19 }, { tileX: 37, tileY: 16 }, { tileX: 38, tileY: 21 }],
    },
];
