export const BUILDING_DEFS = [
    {
        type: 'command',
        x: 18,
        y: 15,
        width: 5,
        height: 4,
        label: 'COMMAND CENTER',
        shortLabel: 'COMMAND',
        icon: 'C',
        description: 'Team status',
        district: 'civic',
        visualTier: 'hero',
        labelPriority: 'landmark',
        entrance: { tileX: 20, tileY: 19 },
        visitTiles: [{ tileX: 20, tileY: 19 }, { tileX: 17, tileY: 19 }, { tileX: 23, tileY: 19 }],
    },
    {
        type: 'chathall',
        x: 13,
        y: 18,
        width: 4,
        height: 3,
        label: 'CITY HALL',
        shortLabel: 'HALL',
        icon: 'M',
        description: 'Messages',
        district: 'civic',
        visualTier: 'major',
        entrance: { tileX: 17, tileY: 19 },
        visitTiles: [{ tileX: 17, tileY: 19 }, { tileX: 15, tileY: 17 }, { tileX: 12, tileY: 19 }],
    },
    {
        type: 'taskboard',
        x: 23,
        y: 22,
        width: 4,
        height: 3,
        label: 'TASK BOARD',
        shortLabel: 'TASKS',
        icon: 'B',
        description: 'Task status',
        district: 'civic',
        visualTier: 'major',
        entrance: { tileX: 25, tileY: 25 },
        visitTiles: [{ tileX: 25, tileY: 25 }, { tileX: 22, tileY: 24 }, { tileX: 27, tileY: 23 }],
    },
    {
        type: 'forge',
        x: 29,
        y: 25,
        width: 4,
        height: 3,
        label: 'CODE FORGE',
        shortLabel: 'FORGE',
        icon: 'F',
        description: 'Code work',
        district: 'workshop',
        visualTier: 'major',
        labelPriority: 'landmark',
        entrance: { tileX: 31, tileY: 24 },
        visitTiles: [{ tileX: 31, tileY: 24 }, { tileX: 29, tileY: 28 }, { tileX: 28, tileY: 28 }],
    },
    {
        type: 'mine',
        x: 5,
        y: 31,
        width: 4,
        height: 3,
        label: 'TOKEN MINE',
        shortLabel: 'MINE',
        icon: 'T',
        description: 'Token usage',
        district: 'resource',
        visualTier: 'major',
        labelPriority: 'landmark',
        entrance: { tileX: 7, tileY: 30 },
        visitTiles: [{ tileX: 7, tileY: 30 }, { tileX: 4, tileY: 33 }, { tileX: 9, tileY: 32 }],
    },
    {
        type: 'archive',
        x: 23,
        y: 16,
        width: 4,
        height: 3,
        label: 'LORE ARCHIVE',
        shortLabel: 'ARCHIVE',
        icon: 'A',
        description: 'Reading and search',
        district: 'civic',
        visualTier: 'major',
        entrance: { tileX: 23, tileY: 19 },
        visitTiles: [{ tileX: 23, tileY: 19 }, { tileX: 27, tileY: 18 }, { tileX: 24, tileY: 15 }],
    },
    {
        type: 'observatory',
        x: 9,
        y: 7,
        width: 4,
        height: 4,
        label: 'RESEARCH OBSERVATORY',
        shortLabel: 'OBSERVATORY',
        icon: '*',
        description: 'External research',
        district: 'knowledge',
        visualTier: 'hero',
        labelPriority: 'landmark',
        entrance: { tileX: 11, tileY: 11 },
        visitTiles: [{ tileX: 11, tileY: 11 }, { tileX: 8, tileY: 10 }, { tileX: 13, tileY: 9 }],
    },
    {
        type: 'portal',
        x: 8,
        y: 27,
        width: 4,
        height: 4,
        label: 'PORTAL GATE',
        shortLabel: 'PORTAL',
        icon: 'O',
        description: 'Browser and remote tools',
        district: 'arcane',
        visualTier: 'hero',
        labelPriority: 'landmark',
        entrance: { tileX: 10, tileY: 26 },
        visitTiles: [{ tileX: 10, tileY: 26 }, { tileX: 7, tileY: 29 }, { tileX: 12, tileY: 30 }],
    },
    {
        type: 'watchtower',
        x: 34,
        y: 14,
        width: 3,
        height: 5,
        label: 'PHAROS COMMIT HARBOR',
        shortLabel: 'COMMIT HARBOR',
        icon: 'L',
        description: 'Commit harbor and sea watch',
        district: 'harbor',
        visualTier: 'hero',
        labelPriority: 'landmark',
        entrance: { tileX: 35, tileY: 19 },
        visitTiles: [{ tileX: 35, tileY: 19 }, { tileX: 37, tileY: 16 }, { tileX: 38, tileY: 21 }],
    },
];
