export const BUILDING_DEFS = [
    {
        type: 'command',
        x: 13,
        y: 16,
        width: 5,
        height: 4,
        label: 'COMMAND CENTER',
        shortLabel: 'COMMAND',
        icon: 'C',
        description: 'Team status',
        district: 'civic',
        capacity: { work: 5, ambient: 3, overflow: 3 },
        visualTier: 'hero',
        labelPriority: 'landmark',
        entrance: { tileX: 16, tileY: 21 },
        visitTiles: [
            { tileX: 16, tileY: 21, facingPoint: { x: 15.5, y: 18.0 } },
            { tileX: 14, tileY: 21, facingPoint: { x: 15.5, y: 18.0 } },
            { tileX: 18, tileY: 21, facingPoint: { x: 15.5, y: 18.0 } },
            { tileX: 15, tileY: 22, facingPoint: { x: 15.5, y: 18.0 } },
            { tileX: 17, tileY: 22, facingPoint: { x: 15.5, y: 18.0 } },
            { tileX: 12, tileY: 18, facingPoint: { x: 15.5, y: 18.0 } },
            { tileX: 12, tileY: 19, facingPoint: { x: 15.5, y: 18.0 } },
            { tileX: 18, tileY: 18, facingPoint: { x: 15.5, y: 18.0 } },
            { tileX: 18, tileY: 19, facingPoint: { x: 15.5, y: 18.0 } },
        ],
        walkExclusion: [{ dx: 0, dy: 4, width: 5, height: 1 }],
        scenery: {
            excludePadding: { x: 2, y: 2 },
            sightline: { x0: 10.5, y0: 12.5, x1: 20.5, y1: 22.5 },
            tallPropClearance: 2,
        },
    },
    {
        type: 'taskboard',
        x: 21,
        y: 31,
        width: 4,
        height: 3,
        label: 'TASK BOARD',
        shortLabel: 'TASKS',
        icon: 'B',
        description: 'Task status',
        district: 'civic',
        capacity: { work: 4, ambient: 2, overflow: 2 },
        visualTier: 'hero',
        labelPriority: 'landmark',
        entrance: { tileX: 23, tileY: 35 },
        visitTiles: [
            { tileX: 23, tileY: 35, facingPoint: { x: 23.0, y: 33.5 } },
            { tileX: 21, tileY: 35, facingPoint: { x: 23.0, y: 33.5 } },
            { tileX: 25, tileY: 35, facingPoint: { x: 23.0, y: 33.5 } },
            { tileX: 22, tileY: 36, facingPoint: { x: 23.0, y: 33.5 } },
            { tileX: 24, tileY: 36, facingPoint: { x: 23.0, y: 33.5 } },
            { tileX: 20, tileY: 32, facingPoint: { x: 23.0, y: 33.5 } },
            { tileX: 20, tileY: 33, facingPoint: { x: 23.0, y: 33.5 } },
            { tileX: 25, tileY: 32, facingPoint: { x: 23.0, y: 33.5 } },
            { tileX: 25, tileY: 33, facingPoint: { x: 23.0, y: 33.5 } },
        ],
        walkExclusion: [{ dx: 0, dy: 3, width: 4, height: 1 }],
        scenery: {
            excludePadding: { x: 1, y: 1 },
            sightline: { x0: 19.5, y0: 28.5, x1: 26.5, y1: 35.5 },
            tallPropClearance: 1,
        },
    },
    {
        type: 'forge',
        x: 26,
        y: 26,
        width: 4,
        height: 3,
        label: 'CODE FORGE',
        shortLabel: 'FORGE',
        icon: 'F',
        description: 'Code work',
        district: 'workshop',
        capacity: { work: 4, ambient: 2, overflow: 2 },
        visualTier: 'major',
        labelPriority: 'landmark',
        entrance: { tileX: 25, tileY: 30 },
        visitTiles: [
            { tileX: 25, tileY: 30, facingPoint: { x: 27.5, y: 27.5 } },
            { tileX: 28, tileY: 30, facingPoint: { x: 27.5, y: 27.5 } },
            { tileX: 24, tileY: 31, facingPoint: { x: 27.5, y: 27.5 } },
            { tileX: 27, tileY: 31, facingPoint: { x: 27.5, y: 27.5 } },
            { tileX: 30, tileY: 31, facingPoint: { x: 27.5, y: 27.5 } },
            { tileX: 25, tileY: 28, facingPoint: { x: 27.5, y: 27.5 } },
            { tileX: 30, tileY: 28, facingPoint: { x: 27.5, y: 27.5 } },
        ],
        walkExclusion: [{ dx: -1, dy: 3, width: 5, height: 1 }],
        scenery: {
            excludePadding: { x: 1, y: 1 },
            sightline: { x0: 23.5, y0: 24.5, x1: 31.5, y1: 30.5 },
            tallPropClearance: 1,
        },
    },
    {
        type: 'mine',
        x: 11,
        y: 31,
        width: 4,
        height: 3,
        label: 'TOKEN MINE',
        shortLabel: 'MINE',
        icon: 'T',
        description: 'Token usage',
        district: 'resource',
        capacity: { work: 3, ambient: 2, overflow: 2 },
        visualTier: 'major',
        labelPriority: 'landmark',
        entrance: { tileX: 13, tileY: 35 },
        visitTiles: [
            { tileX: 13, tileY: 35, facingPoint: { x: 13.0, y: 32.5 } },
            { tileX: 11, tileY: 35, facingPoint: { x: 13.0, y: 32.5 } },
            { tileX: 15, tileY: 35, facingPoint: { x: 13.0, y: 32.5 } },
            { tileX: 12, tileY: 36, facingPoint: { x: 13.0, y: 32.5 } },
            { tileX: 14, tileY: 36, facingPoint: { x: 13.0, y: 32.5 } },
            { tileX: 10, tileY: 33, facingPoint: { x: 13.0, y: 32.5 } },
            { tileX: 15, tileY: 33, facingPoint: { x: 13.0, y: 32.5 } },
        ],
        walkExclusion: [{ dx: 0, dy: 3, width: 4, height: 1 }],
        scenery: {
            excludePadding: { x: 1, y: 1 },
            sightline: { x0: 9.5, y0: 29.5, x1: 16.5, y1: 35.5 },
            tallPropClearance: 1,
        },
    },
    {
        type: 'archive',
        x: 3,
        y: 15,
        width: 5,
        height: 3,
        label: 'GRAND LORE ARCHIVE',
        shortLabel: 'ARCHIVE',
        icon: 'A',
        description: 'Reading and search',
        district: 'knowledge',
        capacity: { work: 4, ambient: 2, overflow: 6 },
        visualTier: 'hero',
        labelPriority: 'landmark',
        entrance: { tileX: 8, tileY: 17 },
        visitTiles: [
            { tileX: 8, tileY: 17, facingPoint: { x: 5.5, y: 16.5 } },
            { tileX: 8, tileY: 16, facingPoint: { x: 5.5, y: 16.5 } },
            { tileX: 8, tileY: 18, facingPoint: { x: 5.5, y: 16.5 } },
            { tileX: 9, tileY: 17, facingPoint: { x: 5.5, y: 16.5 } },
            { tileX: 9, tileY: 18, facingPoint: { x: 5.5, y: 16.5 } },
            { tileX: 8, tileY: 19, facingPoint: { x: 5.5, y: 16.5 } },
            { tileX: 9, tileY: 16, facingPoint: { x: 5.5, y: 16.5 } },
            { tileX: 10, tileY: 17, facingPoint: { x: 5.5, y: 16.5 } },
            { tileX: 10, tileY: 18, facingPoint: { x: 5.5, y: 16.5 } },
        ],
        walkExclusion: [{ dx: 0, dy: 3, width: 5, height: 1 }],
        scenery: {
            excludePadding: { x: 2, y: 2 },
            sightline: { x0: 1.0, y0: 11.0, x1: 10.2, y1: 20.5 },
            tallPropClearance: 2,
        },
    },
    {
        type: 'observatory',
        x: 21,
        y: 14,
        width: 4,
        height: 4,
        label: 'RESEARCH OBSERVATORY',
        shortLabel: 'OBSERVATORY',
        icon: '*',
        description: 'External research and skywatch',
        district: 'knowledge',
        capacity: { work: 3, ambient: 2, overflow: 2 },
        visualTier: 'hero',
        labelPriority: 'landmark',
        entrance: { tileX: 23, tileY: 18 },
        visitTiles: [
            { tileX: 23, tileY: 18, facingPoint: { x: 22.5, y: 16.0 } },
            { tileX: 22, tileY: 19, facingPoint: { x: 22.5, y: 16.0 } },
            { tileX: 24, tileY: 19, facingPoint: { x: 22.5, y: 16.0 } },
            { tileX: 20, tileY: 16, facingPoint: { x: 22.5, y: 16.0 } },
            { tileX: 20, tileY: 17, facingPoint: { x: 22.5, y: 16.0 } },
            { tileX: 21, tileY: 18, facingPoint: { x: 22.5, y: 16.0 } },
            { tileX: 25, tileY: 18, facingPoint: { x: 22.5, y: 16.0 } },
        ],
        walkExclusion: [{ dx: 4, dy: 1, width: 1, height: 3 }],
        scenery: {
            excludePadding: { x: 2, y: 1 },
            sightline: { x0: 19.2, y0: 6.8, x1: 28.8, y1: 19.4 },
            tallPropClearance: 2,
        },
    },
    {
        type: 'portal',
        x: 2,
        y: 29,
        width: 4,
        height: 4,
        label: 'PORTAL GATE',
        shortLabel: 'PORTAL',
        icon: 'O',
        description: 'Browser and remote tools',
        district: 'arcane',
        capacity: { work: 4, ambient: 2, overflow: 2 },
        visualTier: 'hero',
        labelPriority: 'landmark',
        entrance: { tileX: 6, tileY: 34 },
        visitTiles: [
            { tileX: 6, tileY: 34, facingPoint: { x: 3.5, y: 31.0 } },
            { tileX: 2, tileY: 34, facingPoint: { x: 3.5, y: 31.0 } },
            { tileX: 4, tileY: 34, facingPoint: { x: 3.5, y: 31.0 } },
            { tileX: 3, tileY: 35, facingPoint: { x: 3.5, y: 31.0 } },
            { tileX: 5, tileY: 35, facingPoint: { x: 3.5, y: 31.0 } },
            { tileX: 6, tileY: 30, facingPoint: { x: 3.5, y: 31.0 } },
            { tileX: 6, tileY: 32, facingPoint: { x: 3.5, y: 31.0 } },
        ],
        walkExclusion: [{ dx: 0, dy: 4, width: 5, height: 1 }],
        scenery: {
            excludePadding: { x: 1, y: 1 },
            sightline: { x0: 0.5, y0: 27.0, x1: 7.5, y1: 34.5 },
            tallPropClearance: 1,
        },
    },
    {
        type: 'watchtower',
        x: 27,
        y: 8,
        width: 3,
        height: 5,
        label: 'PHAROS LIGHTHOUSE',
        shortLabel: 'LIGHTHOUSE',
        icon: 'L',
        description: 'Sea watch and beacon',
        district: 'harbor',
        capacity: { work: 2, ambient: 1, overflow: 1 },
        visualTier: 'hero',
        labelPriority: 'landmark',
        entrance: { tileX: 28, tileY: 14 },
        visitTiles: [
            { tileX: 28, tileY: 14, facingPoint: { x: 28.0, y: 10.5 } },
            { tileX: 28, tileY: 15, facingPoint: { x: 28.0, y: 10.5 } },
            { tileX: 27, tileY: 15, facingPoint: { x: 28.0, y: 10.5 } },
            { tileX: 29, tileY: 15, facingPoint: { x: 28.0, y: 10.5 } },
        ],
        walkExclusion: [{ dx: 0, dy: 5, width: 3, height: 1 }],
        scenery: {
            excludePadding: { x: 2, y: 2 },
            sightline: { x0: 24.5, y0: 4.5, x1: 32.0, y1: 15.5 },
            tallPropClearance: 2,
        },
    },
    {
        type: 'harbor',
        x: 30,
        y: 17,
        width: 5,
        height: 4,
        label: 'HARBOR MASTER',
        shortLabel: 'HARBOR',
        icon: 'H',
        description: 'Commit ships and push departures',
        district: 'harbor',
        capacity: { work: 4, ambient: 3, overflow: 3 },
        visualTier: 'major',
        labelPriority: 'landmark',
        entrance: { tileX: 29, tileY: 19 },
        visitTiles: [
            { tileX: 29, tileY: 19, facingPoint: { x: 34.0, y: 19.0 } },
            { tileX: 28, tileY: 18, facingPoint: { x: 34.0, y: 19.0 } },
            { tileX: 28, tileY: 20, facingPoint: { x: 34.0, y: 19.0 } },
            { tileX: 27, tileY: 19, facingPoint: { x: 34.0, y: 19.0 } },
            { tileX: 27, tileY: 17, facingPoint: { x: 34.0, y: 19.0 } },
            { tileX: 29, tileY: 21, facingPoint: { x: 34.0, y: 19.0 } },
            { tileX: 28, tileY: 21, facingPoint: { x: 34.0, y: 19.0 } },
        ],
        walkExclusion: [{ dx: -1, dy: 0, width: 1, height: 4 }],
        scenery: {
            excludePadding: { x: 2, y: 1 },
            sightline: { x0: 28.5, y0: 14.5, x1: 36.5, y1: 21.5 },
            tallPropClearance: 2,
        },
    },
];
