// GENERATED by scripts/world/generate-p3-variants.mjs — do not edit by hand.
// 10.3: the Display P3 variant of each reserved status and C4 effect hue
// (DisplayColor P3_RESERVED_HUES through p3RoleInk, the shaders' role chroma),
// drawn on the overlay only while its 2D context is display-p3 and the window
// is on a P3 screen (DisplayColor installP3OverlayInks). Keys are lowercase
// sRGB hex.
export const P3_VARIANTS = Object.freeze({
    '#79d975': 'color(display-p3 0.5180 0.8593 0.4378)',
    '#86bfe0': 'color(display-p3 0.5381 0.7476 0.8977)',
    '#df8c3f': 'color(display-p3 0.8672 0.5412 0.1979)',
    '#e06c5b': 'color(display-p3 0.8671 0.4073 0.3288)',
    '#f06ae0': 'color(display-p3 0.9199 0.3759 0.8996)',
    '#e8d44d': 'color(display-p3 0.9137 0.8329 0.2442)',
    '#7a2e12': 'color(display-p3 0.4725 0.1666 0.0322)',
    '#e8762b': 'color(display-p3 0.9003 0.4472 0.0890)',
    '#ffd27a': 'color(display-p3 0.9976 0.8227 0.4414)',
    '#f2c14e': 'color(display-p3 0.9470 0.7551 0.2510)',
    '#ffb347': 'color(display-p3 0.9941 0.6964 0.2159)',
    '#d94a3a': 'color(display-p3 0.8400 0.2587 0.1869)',
    '#fff3bf': 'color(display-p3 1.0000 0.9549 0.7361)',
});
